import React, { useState, useEffect, useCallback } from "react";
import Navbar from "./Navbar";
import Dashboard from "./Dashboard";
import Deposit from "./Deposit";
import Withdraw from "./Withdraw";
import Transfer from "./Transfer";
import Loans from "./Loans";

// ── ABI imports (generated by `truffle compile`) ───────────────
let BankTokenABI, DecentralizedBankABI;
try {
  BankTokenABI = require("../abis/BankToken.json");
  DecentralizedBankABI = require("../abis/DecentralizedBank.json");
} catch {
  console.warn("⚠ Contract ABIs not found. Run `truffle compile` first.");
}

const TABS = [
  { id: "dashboard", label: "Dashboard", icon: "bi-grid-1x2" },
  { id: "deposit", label: "Deposit", icon: "bi-box-arrow-in-down" },
  { id: "withdraw", label: "Withdraw", icon: "bi-box-arrow-up" },
  { id: "transfer", label: "Transfer", icon: "bi-arrow-left-right" },
  { id: "loans", label: "Loans", icon: "bi-bank2" },
];

function App() {
  // ── State ──────────────────────────────────────────────────
  const [web3, setWeb3] = useState(null);
  const [account, setAccount] = useState("");
  const [ethBalance, setEthBalance] = useState("0");
  const [bnkBalance, setBnkBalance] = useState("0"); // wallet BNK
  const [bankBalance, setBankBalance] = useState("0"); // deposited BNK
  const [loanBalance, setLoanBalance] = useState("0");
  const [bankToken, setBankToken] = useState(null);
  const [bank, setBank] = useState(null);
  const [networkId, setNetworkId] = useState(null);
  const [activeTab, setActiveTab] = useState("dashboard");
  const [transactions, setTransactions] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  // ── Refresh all balances ───────────────────────────────────
  const refreshBalances = useCallback(
    async (w3, acct, tokenContract, bankContract) => {
      try {
        const eth = await w3.eth.getBalance(acct);
        setEthBalance(w3.utils.fromWei(eth, "ether"));

        const bnk = await tokenContract.methods.balanceOf(acct).call();
        setBnkBalance(w3.utils.fromWei(bnk, "ether"));

        const bbal = await bankContract.methods.getBalance(acct).call();
        setBankBalance(w3.utils.fromWei(bbal, "ether"));

        const loan = await bankContract.methods.getLoanAmount(acct).call();
        setLoanBalance(w3.utils.fromWei(loan, "ether"));
      } catch (err) {
        console.error("Balance refresh error:", err);
      }
    },
    []
  );

  // ── Switch MetaMask to Ganache ───────────────────────────────
  const switchToGanache = async () => {
    const GANACHE_CHAIN_ID = "0x1691"; // 5777 in hex (matches user Ganache)
    try {
      await window.ethereum.request({
        method: "wallet_switchEthereumChain",
        params: [{ chainId: GANACHE_CHAIN_ID }],
      });
    } catch (switchError) {
      // Chain not added yet — add it automatically
      if (switchError.code === 4902 || switchError.code === -32603) {
        await window.ethereum.request({
          method: "wallet_addEthereumChain",
          params: [{
            chainId: GANACHE_CHAIN_ID,
            chainName: "Ganache Local",
            rpcUrls: ["http://127.0.0.1:7545"],
            nativeCurrency: { name: "ETH", symbol: "ETH", decimals: 18 },
          }],
        });
      } else {
        throw switchError;
      }
    }
  };

  // ── Connect Wallet ─────────────────────────────────────────
  const connectWallet = useCallback(async () => {
    if (!window.ethereum) {
      setError("MetaMask is not installed. Please install MetaMask to continue.");
      return;
    }
    if (!BankTokenABI || !DecentralizedBankABI) {
      setError("Contract ABIs not found. Please run `truffle compile` and `truffle migrate` first.");
      return;
    }

    setLoading(true);
    setError("");

    try {
      // Step 1: Switch MetaMask to Ganache network automatically
      await switchToGanache();

      // Step 2: Connect with MetaMask (now on Ganache)
      const Web3 = window.Web3;
      const w3 = new Web3(window.ethereum);
      const accounts = await window.ethereum.request({
        method: "eth_requestAccounts",
      });
      const acct = accounts[0];
      const netId = await w3.eth.net.getId();
      console.log("Connected to Network ID:", netId);

      // Load contract instances — try exact network ID first,
      // then fall back to the last deployed network (handles Ganache ID mismatches)
      const getNetworkData = (artifact) => {
        if (artifact.networks[netId]) return artifact.networks[netId];
        const networkIds = Object.keys(artifact.networks);
        if (networkIds.length > 0) {
          const lastId = networkIds[networkIds.length - 1];
          console.log(`Contract not found on network ${netId}, using deployment from network ${lastId}`);
          return artifact.networks[lastId];
        }
        return null;
      };

      const tokenNetData = getNetworkData(BankTokenABI);
      const bankNetData = getNetworkData(DecentralizedBankABI);

      if (!tokenNetData || !bankNetData) {
        setError(
          `Contracts not deployed. Please run: truffle migrate --reset`
        );
        setLoading(false);
        return;
      }

      const tokenContract = new w3.eth.Contract(
        BankTokenABI.abi,
        tokenNetData.address
      );
      const bankContract = new w3.eth.Contract(
        DecentralizedBankABI.abi,
        bankNetData.address
      );

      setWeb3(w3);
      setAccount(acct);
      setNetworkId(netId);
      setBankToken(tokenContract);
      setBank(bankContract);

      await refreshBalances(w3, acct, tokenContract, bankContract);
    } catch (err) {
      console.error("Connection error:", err);
      setError(err.message || "Failed to connect wallet");
    }

    setLoading(false);
  }, [refreshBalances]);

  // ── Listen for MetaMask events ─────────────────────────────
  useEffect(() => {
    if (!window.ethereum) return;

    const handleAccountsChanged = (accounts) => {
      if (accounts.length === 0) {
        // Disconnected
        setAccount("");
        setBankToken(null);
        setBank(null);
      } else {
        setAccount(accounts[0]);
        if (web3 && bankToken && bank) {
          refreshBalances(web3, accounts[0], bankToken, bank);
        }
      }
    };

    const handleChainChanged = () => {
      window.location.reload();
    };

    window.ethereum.on("accountsChanged", handleAccountsChanged);
    window.ethereum.on("chainChanged", handleChainChanged);

    return () => {
      window.ethereum.removeListener("accountsChanged", handleAccountsChanged);
      window.ethereum.removeListener("chainChanged", handleChainChanged);
    };
  }, [web3, bankToken, bank, refreshBalances]);

  // ── Add transaction to history ─────────────────────────────
  const addTransaction = (type, amount, txHash) => {
    setTransactions((prev) => [
      { type, amount, txHash, timestamp: new Date().toISOString() },
      ...prev.slice(0, 49),
    ]);
  };

  // ── Trigger balance refresh (passed to child components) ───
  const onTxComplete = () => {
    if (web3 && account && bankToken && bank) {
      refreshBalances(web3, account, bankToken, bank);
    }
  };

  // ── Shared props for child components ──────────────────────
  const childProps = {
    web3,
    account,
    bankToken,
    bank,
    ethBalance,
    bnkBalance,
    bankBalance,
    loanBalance,
    onTxComplete,
    addTransaction,
    transactions,
  };

  // ── Render ─────────────────────────────────────────────────
  const renderTab = () => {
    switch (activeTab) {
      case "dashboard":
        return <Dashboard {...childProps} />;
      case "deposit":
        return <Deposit {...childProps} />;
      case "withdraw":
        return <Withdraw {...childProps} />;
      case "transfer":
        return <Transfer {...childProps} />;
      case "loans":
        return <Loans {...childProps} />;
      default:
        return <Dashboard {...childProps} />;
    }
  };

  return (
    <div className="app">
      <Navbar
        account={account}
        ethBalance={ethBalance}
        networkId={networkId}
        onConnect={connectWallet}
        loading={loading}
      />

      <main className="container py-4">
        {error && (
          <div className="alert-bank error mb-lg">
            <i className="bi bi-exclamation-triangle-fill"></i>
            {error}
            <button
              onClick={() => setError("")}
              style={{
                marginLeft: "auto",
                background: "none",
                border: "none",
                color: "inherit",
                cursor: "pointer",
                fontSize: "1.1rem",
              }}
            >
              <i className="bi bi-x-lg"></i>
            </button>
          </div>
        )}

        {!account ? (
          <div className="welcome-screen">
            <div className="welcome-logo">
              <i className="bi bi-bank"></i>
            </div>
            <h1>
              Welcome to <span className="text-gradient">BlockBank</span>
            </h1>
            <p>
              Your decentralized gateway to banking on the Ethereum blockchain.
              Deposit, withdraw, transfer BNK tokens, and manage loans — all
              secured by smart contracts.
            </p>
            <button
              className="btn-connect"
              onClick={connectWallet}
              disabled={loading}
              id="btn-connect-wallet"
            >
              {loading ? (
                <>
                  <span className="spinner-bank"></span> Connecting…
                </>
              ) : (
                <>
                  <i className="bi bi-wallet2"></i> Connect MetaMask
                </>
              )}
            </button>
          </div>
        ) : (
          <>
            {/* Tab Navigation */}
            <nav className="tab-nav" id="main-tabs">
              {TABS.map((tab) => (
                <button
                  key={tab.id}
                  className={`tab-nav-btn ${
                    activeTab === tab.id ? "active" : ""
                  }`}
                  onClick={() => setActiveTab(tab.id)}
                  id={`tab-${tab.id}`}
                >
                  <i className={`bi ${tab.icon}`}></i>
                  {tab.label}
                </button>
              ))}
            </nav>

            {/* Active Tab Content */}
            {renderTab()}
          </>
        )}
      </main>
    </div>
  );
}

export default App;
